Algoritmo "consumo"

Var
        distanciaPer: inteiro
        gasto: real
        consumo: real
        
        


Inicio
                 escreva("Distancia percorrida: ")
                 leia(distanciaPer)
                 escreva("Combustítvel gasto: ")
                 leia(gasto)
                 
                 
                 consumo <- distanciaPer / gasto
                 
                 escreval("Consumo Médio: ", consumo:2:3)


Fimalgoritmo